"""Generate ``decisions.md``, the ADR index over ``docs/project_notes/decisions/``.

Each ADR is one file under ``decisions/`` (``ADR-NNN-slug.md``).
``decisions.md`` holds nothing but the preamble and this generated index, so
a session loads a small index and then reads exactly one ADR, instead of
grepping a monolith for a line range.

    kmem notes index

Links are file paths, not in-file anchors, so a reader can open the ADR
directly. Level-3 sub-headings (``### ADR-102 addendum``) live inside their
parent's file and are linked ``path#anchor``.

The audit check ``docs_adr_index_fresh`` compares ``render_index`` with the
file on disk, so every function here takes the notes directory explicitly.
"""

from __future__ import annotations

import re
from pathlib import Path

START = "<!-- ADR-INDEX:START (generated by kmem notes index; do not hand-edit) -->"
END = "<!-- ADR-INDEX:END -->"

HEADING_RE = re.compile(r"^(#{2,3})\s+(ADR-.*)$")
FIELD_RE = re.compile(r"^\*\*(Status|Date)\*\*:\s*(.+?)\s*$")

DEFAULT_PREAMBLE = "# Architectural Decision Records\n\n"


def github_anchor(heading_text: str) -> str:
    """GitHub slug: lowercase, drop non-word/space/hyphen chars, spaces->hyphens."""
    s = heading_text.strip().lower()
    s = re.sub(r"[^\w\s-]", "", s)
    return s.replace(" ", "-")


def adr_sort_key(path: Path):
    m = re.match(r"ADR-(\d+)(?:-phase-(\d+))?", path.name, re.I)
    if not m:
        return (10**9, 0, path.name)
    return (int(m.group(1)), int(m.group(2) or 0), path.name)


def rows_for(path: Path) -> list[tuple[str, str, str, str, str]]:
    """(level, title, status, date, link) for each ADR heading in one file."""
    lines = path.read_text(encoding="utf-8").split("\n")
    found = []
    for i, line in enumerate(lines):
        m = HEADING_RE.match(line)
        if not m:
            continue
        level, title = m.group(1), m.group(2).strip()
        status = date = ""
        for nxt in lines[i + 1:]:
            if HEADING_RE.match(nxt):
                break
            fm = FIELD_RE.match(nxt.strip())
            if fm:
                if fm.group(1) == "Status":
                    status = status or fm.group(2)
                else:
                    date = date or fm.group(2)
        link = f"decisions/{path.name}"
        if level == "###":
            link += f"#{github_anchor(title)}"
        found.append((level, title, status, date, link))
    return found


def render_index(notes_dir: Path) -> tuple[str, int, int]:
    """Return (full decisions.md text, row count, file count) without writing."""
    notes_dir = Path(notes_dir)
    adr_dir = notes_dir / "decisions"
    decisions = notes_dir / "decisions.md"
    if not adr_dir.is_dir():
        raise FileNotFoundError(f"{adr_dir} not found")

    files = sorted(adr_dir.glob("ADR-*.md"), key=adr_sort_key)
    if not files:
        raise FileNotFoundError(f"no ADR-*.md files in {adr_dir}")

    rows = [r for f in files for r in rows_for(f)]

    out = [START,
           "",
           f"**ADR index ({len(rows)} entries over {len(files)} files)**, generated. "
           "Load this, then read the ONE ADR you need by its path; never the whole corpus. "
           "Regenerate with `kmem notes index` after adding or renaming an ADR file.",
           "",
           "| ADR | Title | Status | Date |",
           "|---|---|---|---|"]
    for level, title, status, date, link in rows:
        num, _, rest = title.partition(":")
        label = num.strip() if rest else title
        desc = rest.strip() if rest else ""
        prefix = "↳ " if level == "###" else ""
        out.append(f"| [{prefix}{label}]({link}) | {desc} | {status or '-'} | {date or '-'} |")
    out += ["", END, ""]
    block = "\n".join(out)

    # Keep whatever preamble already sits above the index (title + conventions).
    preamble = DEFAULT_PREAMBLE
    if decisions.exists():
        existing = decisions.read_text(encoding="utf-8")
        if START in existing:
            preamble = existing[:existing.index(START)]

    return preamble + block, len(rows), len(files)


def write_index(notes_dir: Path) -> tuple[int, int, int]:
    """Write decisions.md; return (rows, files, bytes)."""
    text, n_rows, n_files = render_index(notes_dir)
    target = Path(notes_dir) / "decisions.md"
    target.write_text(text, encoding="utf-8")
    return n_rows, n_files, target.stat().st_size
